blank_issues_enabled: false
contact_links:
  - name: 💬 Questions or Ideas
    url: https://github.com/dgtlinf/user-onboarding/discussions
    about: For general questions, ideas, or feature requests — use Discussions.
