name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_sqlite, bcmath
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run Pest tests
        run: vendor/bin/pest --no-coverage --cache-directory=.phpunit.cache
